import './globals.css'
import type { Metadata } from 'next'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { Providers } from './store/provider'

export const metadata: Metadata = {
  title: 'Blog Presss',
  description: 'Generated by Bahar Keshavarz',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <Providers>{children}</Providers>
        <Footer/>
      </body>
    </html>
  )
}
